# log_file_path: Path to the file where logs will be saved
log_file_path: "~/typotracker_log.txt"

# keyboard_name: Keyboard name to record
keyboard_name: "standard keyboard"

# trigger_key: Key bindings to trigger TypoTracker
trigger_key:
  ctrl: True  # Whether the Ctrl key is included in the trigger
  shift: True  # Whether the Shift key is included in the trigger
  alt: False  # Whether the Alt key is included in the trigger
  cmd: False  # Whether the Cmd key is included in the trigger (mainly for Mac)
  key: ';'  # Specific key for the trigger (in this case, the ';' key)

# notification_type: Type of notification system to use ('macOS', 'Windows', 'Linux', 'None')
notification_type: 'None'

# debug_mode: Enable or disable debug mode (True to enable)
debug_mode: False

# timer_delay: Delay in seconds before logging the typo after detection
timer_delay: 0

# max_size: Maximum size of the key log (older logs are deleted when exceeding this size)
max_size: 1000

# additional_window_size: Number of additional keystrokes to include in the log when a typo is detected
additional_window_size: 12

